services:
  - type: web
    name: houndr-demo
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: false
    customDomains:
      - demo.houndr.ai
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: GENERATE_SOURCEMAP
        value: false
      - key: VITE_APP_URL
        value: https://demo.houndr.ai
